kind: pipeline
type: docker
name: CD

trigger:
  branch:
    - main
  event:
    - push

clone:
  disable: false

steps:
  - name: deploy
    image: node:16
    depends_on: [clone]
    commands:
      - echo get
