name: Rollback
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'choose an release to deploy'
        required: true
        default: 'warning'
jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Version: ${{VERSION}}"
