name: Rollback
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'choose a version to deploy'
        required: true
        default: 'warning'
jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Version
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Version: $VERSION"
      - name: Checkout repository
        uses: actions/checkout@v2
        ref: ${{ github.event.inputs.version }}
